import { LootTable } from './classes/LootTable';
import {
    animalCrateLoot,
    bearLoot,
    bunnyLoot,
    catLoot,
    cheetahLoot,
    crocodileLoot,
    dogLoot,
    dragonLoot,
    elephantLoot,
    foxLoot,
    giraffeLoot,
    goldFishLoot,
    hamsterLoot,
    hippoLoot,
    horseLoot,
    jaguarLoot,
    lionLoot,
    mouseLoot,
    parrotLoot,
    phoenixLoot,
    ponyLoot,
    ratLoot,
    rhinoLoot,
    salamanderLoot,
    tigerLoot,
    unicornLoot,
    wolfLoot,
    wyvernLoot,
    zebraLoot,
} from './loot';

export const animalTable = new LootTable([
    dogLoot,
    catLoot,
    bunnyLoot,
    goldFishLoot,
    hamsterLoot,
    ratLoot,
    mouseLoot,
    parrotLoot,
    foxLoot,
    wolfLoot,
    horseLoot,
    ponyLoot,
    bearLoot,
    lionLoot,
    tigerLoot,
    jaguarLoot,
    elephantLoot,
    rhinoLoot,
    giraffeLoot,
    cheetahLoot,
    salamanderLoot,
    zebraLoot,
    hippoLoot,
    crocodileLoot,
    unicornLoot,
    dragonLoot,
    phoenixLoot,
    wyvernLoot,
]);

export const lootboxTable = new LootTable([animalCrateLoot]);
